### ISSUE TITLE
Get read-the-docs up and running 

### ISSUE THREAD

**Issue by JoshuaSteer** [JoshuaSteer/ampscan#27]
read-the-docs currently points to gitlab, now need to setup with github

**Comment by jack-parsons** [comment]
@JoshuaSteer I don't have access to the current read-the-docs dashboard, so can't change where the docs point to as the name 'AmpScan' is already taken. I believe you can change this if you go to https://readthedocs.org/dashboard/ and change the url it changes to.

**Comment by JoshuaSteer** [comment]
Good point - I'll sort tonight

**Comment by JoshuaSteer** [comment]
@jack-parsons access now added on rtd and I've changed the repo pointer to github, let me know if you have any problems accessing

**Comment by jack-parsons** [comment]
![image](https://user-images.githubusercontent.com/7894397/62136864-deadeb80-b2dc-11e9-8e82-fc2cc0a569b8.png)
Read the docs is now building successfully
